# Generated by Django 5.0.6 on 2024-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Monthly",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("january", models.CharField(max_length=100)),
                ("febuary", models.CharField(max_length=100)),
                ("march", models.CharField(max_length=100)),
                ("april", models.CharField(max_length=100)),
                ("may", models.CharField(max_length=100)),
                ("june", models.CharField(max_length=100)),
                ("july", models.CharField(max_length=100)),
                ("august", models.CharField(max_length=100)),
                ("september", models.CharField(max_length=100)),
                ("october", models.CharField(max_length=100)),
                ("november", models.CharField(max_length=100)),
                ("december", models.CharField(max_length=100)),
            ],
        ),
    ]
